### PR TITLE
fix(#198): improve empty attribute behavior

### LINKED ISSUE #198: 🐛 BUG: Markdown `Expected "=>" but found end of file`
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Markdown with `({})` in it causes exception:

```
 𝘅 Expected "=>" but found end of file

   > 1 | ({})
       |     ^

file:///Users/xxx/astro-bug-arrow-expected/node_modules/astro/dist/compiler/codegen/index.js:213
    throw new Error(`Unable to compile expression`);
          ^
```

### Steps to Reproduce

```sh
git clone git@github.com:amatiasq/astro-bug-arrow-expected.git
cd astro-bug-arrow-expected
npm i
npm start
```

### Expected result
It should render an HTML with `({})`

### Actual behaviour
```
[13:36:02] [snowpack] File changed: src/pages/index.md
[access] /
[parse-error] 

 /Users/xxx/astro-bug-arrow-expected/src/pages/index.md:1:7

 𝘅 Expected "=>" but found end of file

   > 1 | ({})
       |     ^

file:///Users/xxx/astro-bug-arrow-expected/node_modules/astro/dist/compiler/codegen/index.js:213
    throw new Error(`Unable to compile expression`);
          ^

Error: Unable to compile expression
    at compileExpression (file:///Users/xxx/astro-bug-arrow-expected/node_modules/astro/dist/compiler/codegen/index.js:213:11)
    at async Object.enter (file:///Users/xxx/astro-bug-arrow-expected/node_modules/astro/dist/compiler/codegen/index.js:464:24)
    at async AsyncWalker.visit (file:///Users/xxx/astro-bug-arrow-expected/node_modules/estree-walker/src/async.js:49:5)
    at async AsyncWalker.visit (file:///Users/xxx/astro-bug-arrow-expected/node_modules/estree-walker/src/async.js:86:6)
    at async AsyncWalker.visit (file:///Users/xxx/astro-bug-arrow-expected/node_modules/estree-walker/src/async.js:79:14)
    at async AsyncWalker.visit (file:///Users/xxx/astro-bug-arrow-expected/node_modules/estree-walker/src/async.js:79:14)
    at async asyncWalk (file:///Users/xxx/astro-bug-arrow-expected/node_modules/estree-walker/src/index.js:34:9)
```

### Link to Minimal Reproducible Example (Optional)

https://github.com/amatiasq/astro-bug-arrow-expected

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Closes #198
- Treats `{}` as valid to avoid generating invalid JS when encountered
- It is treated equivalent to `{undefined}`

Curious what folks think the correct behavior is here? Should we handle this as `${undefined}` or `${}` (invalid JS) or throw a panic?

## Testing

Tests added

## Docs

No docs, this isn't an official feature

### CODE REVIEW

**Review by drwpow — APPROVED** [review]

**Review by jonathantneal — APPROVED** [review]
This is a nice touch.

File: internal/printer/print-to-js.go [hunk 1]
```diff
@@ -293,6 +293,8 @@ func render1(p *printer, n *Node, opts RenderOptions) {
 	if n.Expression {
 		if n.FirstChild != nil {
 			p.print("${")
+		} else {
+			p.print("${undefined")
```
Comment (jonathantneal) [inline internal/printer/print-to-js.go:297]: Nit pick:

```suggestion
			p.print("${void 0")
 ```
 
 Wouldn’t want someone redefining `undefined` for fun side-effects.

**Review by jonathantneal — APPROVED** [review]

File: internal/printer/print-to-js.go (hunk 1 above)
Comment (natemoo-re) [reply internal/printer/print-to-js.go]: Smart!
