### PR TITLE
fix(#413): fix wasm `parse` to save attribute namespace

### LINKED ISSUE #413: 🐛 BUG: wasm `parse()` does not return the attribute namespace.
### What version of `@astrojs/compiler` are you using?

0.15.1

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The namespace is not included in the attribute node of AST obtained by the wasm `parse` method.

I think the name of the AST node for the third attribute in the following example should be `xmlns:xlink`.
(Or we need the namespace property? )

Example:

```astro
<svg 
  viewBox="0 0 147 40"
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">
</svg>
```

AST:

```json
{
  "type": "root",
  "children": [
    {
      "type": "element",
      "name": "svg",
      "attributes": [
        {
          "type": "attribute",
          "kind": "quoted",
          "name": "viewBox",
          "value": "0 0 147 40"
        },
        {
          "type": "attribute",
          "kind": "quoted",
          "name": "xmlns",
          "value": "http://www.w3.org/2000/svg"
        },
        {
          "type": "attribute",
          "kind": "quoted",
          "name": "xlink",
          "value": "http://www.w3.org/1999/xlink"
        }
      ],
      "children": [
        {
          "type": "text",
          "value": "\n"
        }
      ]
    },
    {
      "type": "text",
      "value": "\n"
    }
  ]
}
```

We probably need to handle the namespace in the following places:

https://github.com/withastro/compiler/blob/d5dd438d3f0aa5f005e9b4d7127230711ab126a1/internal/printer/print-to-json.go#L207-L213

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-au6cvz?file=src%2Fpages%2Findex.astro&on=stackblitz

https://github.com/ota-meshi/withastro-compiler-bug-2022-05-31

### PR DESCRIPTION
**Pull request by ota-meshi**
## Changes

Fixes #413

This PR fixes the wasm `parse` method to save the attribute namespace.

## Testing

I added a test case for a template with attribute namespace to `internal/printer/printer_test.go TestPrintToJSON` and verified that `go test -v ./internal/...` command passed.

## Docs

bug fix only.

---

I'm not familiar with the go lang, so I don't know best practices such as variable declarations. If I'm doing something strange by convention, please let me know.

### CODE REVIEW

File: internal/printer/print-to-json.go [hunk 1]
```diff
@@ -204,11 +204,17 @@ func renderNode(p *printer, parent *ASTNode, n *Node, opts t.ParseOptions) {
 			}
 
 			for _, attr := range n.Attr {
+				var name string
+				if attr.Namespace != "" {
+					name = attr.Namespace + ":" + attr.Key
+				} else {
+					name = attr.Key
+				}
```
Comment (natemoo-re) [inline internal/printer/print-to-json.go:212]: Definitely nothing wrong with your approach but I would find this a little bit cleaner!

- Assign to `name` only if `attr.Namespace != ""`
- Use `fmt.Sprintf()` to concat namespace and key.

```suggestion
				name := attr.Key
				if attr.Namespace != "" {
					name = fmt.Sprintf("%s:%s", attr.Namespace, attr.Key)
				}
```

**Review by natemoo-re — APPROVED** [review]
This is a clean fix, thank you!
