### PR TITLE
fix: return error instead of panic for missing frontmatter fence

### LINKED ISSUE #1038: 🐛 BUG: panic: html: bad parser state: originalIM was set twice [recovered]         panic: interface conversion: string is not error: missing method Error
### What version of `@astrojs/compiler` are you using?

2.10.1

### What package manager are you using?

npm

### What operating system are you using?

wsl2

### Describe the Bug

```
`panic: html: bad parser state: originalIM was set twice [recovered]
        panic: interface conversion: string is not error: missing method Error

goroutine 8 [running]:
main.main.Transform.func1.1.1.1()
        ./astro-wasm.go:327 +0x5
panic({0x17900, 0x7b180})
        runtime/panic.go:770 +0x1a
github.com/withastro/compiler/internal.(*parser).setOriginalIM(...)
        github.com/withastro/compiler/internal/parser.go:544
github.com/withastro/compiler/internal.inBodyIM(0x14565a0)
        github.com/withastro/compiler/internal/parser.go:1105 +0x3f8
github.com/withastro/compiler/internal.(*parser).parseCurrentToken(0x14565a0)
        github.com/withastro/compiler/internal/parser.go:2981 +0x12
github.com/withastro/compiler/internal.(*parser).parse(0x14565a0)
        github.com/withastro/compiler/internal/parser.go:3008 +0x3
github.com/withastro/compiler/internal.ParseWithOptions({0x7b9c8, 0x1434260}, {0x14b9e20, 0x1, 0x1})
        github.com/withastro/compiler/internal/parser.go:3072 +0x13
main.main.Transform.func1.1.1()
        ./astro-wasm.go:332 +0x4
created by main.main.Transform.func1.1 in goroutine 6
        ./astro-wasm.go:323 +0x7
exit code: 2
24:09:23 [ERROR] [UnknownCompilerError] Cannot read properties of undefined (reading 'exports')
  Hint:
    This is almost always a problem with the Astro compiler, not your code. Please open an issue at https://astro.build/issues/compiler.
  Error reference:
    https://docs.astro.build/en/reference/errors/unknown-compiler-error/
  Stack trace:
    at syscall/js.valueNew (file:///home/lilith/work/imazen-web/node_modules/@astrojs/compiler/dist/chunk-W5DTLHV4.js:1:4526)
    at wasm://wasm/0138ceae:wasm-function[1567]:0x168b12
    at wasm://wasm/0138ceae:wasm-function[1543]:0x164c04
    at wasm://wasm/0138ceae:wasm-function[1169]:0xfab0e
    [...] See full stack trace in the browser, or rerun with --verbose.`
```

### Link to Minimal Reproducible Example

mailto:lilith@imazen.io

### LINKED ISSUE #1094: 🐛 BUG: Critical Compiler Panic on Windows: bad parser state & cannot read 'exports'
### What version of `@astrojs/compiler` are you using?

2.12.2

### What package manager are you using?

npm

### What operating system are you using?

windows

### What is the bug?

I am experiencing a persistent, critical compiler bug on my Windows 11 machine that makes Astro completely unusable for my project. The development server will not start and consistently throws a low-level `panic` error.

### The Error Messages

The primary crash is a Go panic: `panic: html: bad parser state: originalIM was set twice`

This results in the user-facing error: `UnknownCompilerError: Cannot read properties of undefined (reading 'exports')`.

The error always points to my `src/layouts/Layout.astro` file, but the trigger seems to be the CSS import.

### What I Have Tried (Everything)

I have worked extensively with an AI assistant to solve this, and we have tried every possible solution. The bug still remains. We have tried:

1.  **Creating a brand new, empty Astro project.** The error still happens as soon as I try to build my layout.
2.  **Completely uninstalling Node.js**, manually deleting all `npm` and `npm-cache` folders from `%appdata%`, and reinstalling the latest Node.js LTS version. The bug remains.
3.  **Cleaning the npm cache** with `npm cache clean --force`.
4.  **Moving the project to a path with no spaces** (e.g., `C:/dev/project`).
5.  **Recreating the `Layout.astro` file from scratch** with minimal code.
6.  **Isolating the trigger:**
    -   A bare-bones `Layout.astro` file *without any imports* works.
    -   The server crashes as soon as I add the line `import "../styles/global.css";` to the layout.
    -   We found and fixed a syntax error in the `global.css` file, but the `panic` still occurs when importing the corrected CSS file.

### Conclusion

There is a fundamental incompatibility between the Astro WASM compiler and something within my project's CSS file or dependency graph that is causing a non-recoverable crash. The tool is failing at a level that is impossible for me to debug further. My project is currently completely blocked. Please help.

### Link to Minimal Reproducible Example

Cannot reproduce online. Bug is local to my Windows machine. See steps in description.

### LINKED ISSUE #1107: 🐛 BUG:
### What version of `@astrojs/compiler` are you using?

2.12.2

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

<html><body>
<pre class="c_mu c_jk c_bw c_eb c_sn c_so c_sp c_sq c_qv c_sr c_ss c_st c_su c_sv">
✗ Build failed in 2.11s
--
14:39:39.822 | [UnknownCompilerError] [astro:build] Cannot read properties of undefined (reading 'exports')
14:39:39.822 | file: /opt/buildhome/repo/src/components/TableOfContents.astro:undefined:undefined
14:39:39.822 | Hint:
14:39:39.822 | This is almost always a problem with the Astro compiler, not your code. Please open an issue at https://astro.build/issues/compiler.
14:39:39.822 | Error reference:
14:39:39.822 | https://docs.astro.build/en/reference/errors/unknown-compiler-error/
14:39:39.822 | Location:
14:39:39.822 | /opt/buildhome/repo/src/components/TableOfContents.astro:0:0
14:39:39.822 | Stack trace:
14:39:39.822 | at syscall/js.valueNew (file:///opt/buildhome/repo/node_modules/@astrojs/compiler/dist/chunk-W5DTLHV4.js:1:4526)
14:39:39.823 | at wasm://wasm/01395692:wasm-function[1567]:0x168afa
14:39:39.823 | at wasm://wasm/01395692:wasm-function[1543]:0x164bec
14:39:39.823 | at wasm://wasm/01395692:wasm-function[1169]:0xfaaf6
14:39:39.823 | at Object.transform (file:///opt/buildhome/repo/node_modules/@astrojs/compiler/dist/chunk-W5DTLHV4.js:1:6575)
14:39:40.247 | Failed: error occurred while running build command

</pre>
</body>
</html>

### Link to Minimal Reproducible Example

https://waste-management.brian-2cd.workers.dev/

### LINKED ISSUE #1133: 🐛 BUG:Astro Compiler Panic "originalIM was set twice"
### What version of `@astrojs/compiler` are you using?

2.13.0

### What package manager are you using?

bun1.3.7

### What operating system are you using?

Linux

### Describe the Bug

it got me worried for an hour i tried to change some logic but to no avail the error still persisted but then i looked again at the panic msg and it says missing something so i started removing code blocks and import statements.

i have no idea just know that i belive the parser state machine expects something else first  instead of the import statement maybe something else.

```
panic: html: bad parser state: originalIM was set twice [recovered]
        panic: interface conversion: string is not error: missing method Error

goroutine 7 [running]:
main.main.Transform.func1.1.1.1()
        ./astro-wasm.go:335 +0x5
panic({0x17940, 0x7b460})
        runtime/panic.go:770 +0x1a
github.com/withastro/compiler/internal.(*parser).setOriginalIM(...)
        github.com/withastro/compiler/internal/parser.go:545
github.com/withastro/compiler/internal.inBodyIM(0x1456360)
        github.com/withastro/compiler/internal/parser.go:1106 +0x41a
github.com/withastro/compiler/internal.(*parser).parseCurrentToken(0x1456360)
        github.com/withastro/compiler/internal/parser.go:3009 +0x12
github.com/withastro/compiler/internal.(*parser).parse(0x1456360)
        github.com/withastro/compiler/internal/parser.go:3036 +0x3
github.com/withastro/compiler/internal.ParseWithOptions({0x7bca8, 0x1434100}, {0x1445e20, 0x1, 0x1})
        github.com/withastro/compiler/internal/parser.go:3100 +0x13
main.main.Transform.func1.1.1()
        ./astro-wasm.go:340 +0x4
created by main.main.Transform.func1.1 in goroutine 6
        ./astro-wasm.go:331 +0x7
exit code: 2
19:20:36 [ERROR] [vite] ✗ Build failed in 307ms
[UnknownCompilerError] [astro:build] Cannot read properties of undefined (reading 'exports')
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ygrt2umj?file=src%2Fpages%2Fcheckthis.astro

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- When a file has a closing frontmatter fence (`---`) without an opening fence, the parser would panic with `originalIM was set twice`
- This change detects that invalid state in `inBodyIM` and returns a helpful diagnostic error instead of panicking
- Added new error code `ERROR_MISSING_FRONTMATTER_FENCE` (1006)
- The error message includes a hint telling users to add `---` at the beginning of their file

Fixes #1133
Fixes #1038
Fixes #1094
Fixes #1107

## Testing

Added test case in `packages/compiler/test/errors/missing-frontmatter-fence.ts` that verifies:
- The compiler no longer panics
- A diagnostic with code 1006 is returned
- The error text and hint are correct

## Docs

Bug fix only - no documentation changes needed.

### CODE REVIEW

File: internal/parser.go [hunk 1]
```diff
@@ -1103,6 +1103,19 @@ func copyAttributes(dst *Node, src Token) {
...
+		// If originalIM is already set, we have a closing fence without an opening one
+		if p.originalIM != nil {
+			p.handler.AppendError(&loc.ErrorWithRange{
+				Code: loc.ERROR_MISSING_FRONTMATTER_FENCE,
+				Text: "The closing frontmatter fence (---) is missing an opening fence",
+				Hint: "Add --- at the beginning of your file before any import statements or code",
+				Range: loc.Range{
+					Loc: p.tok.Loc,
+					Len: 3,
+				},
```
Comment (ematipico) [inline internal/parser.go]: Do we have snapshot tests so that we can verify that the range is correct?
