### PR TITLE
Maintain whitespace before tag close

### LINKED ISSUE #801: 🐛 BUG: [TSX] Spaces in tag names are not preserved unless there's an attribute
### What version of `@astrojs/compiler` are you using?

1.5.0

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### Describe the Bug

`<Button ></Button>` gets transformed into `<Button></Button>` (note the missing space), as such, when asking completions here: `<Button |>`, you get unexpected things because it's trying to complete the component's tag, and not a value at the requested position 
image

image

Cause of https://github.com/withastro/language-tools/issues/566

### Link to Minimal Reproducible Example

See description

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Resolves #801
- Maintains trailing whitespace in TSX output, which fixes TS completions in some cases

## Testing

Two tests added

## Docs

N/A, bug fix only

### CODE REVIEW

File: internal/printer/print-to-tsx.go [hunk 1]
```diff
@@ -375,15 +375,13 @@ declare const Astro: Readonly<import('astro').AstroGlobal<%s>>`, props.Ident)
 			p.print(`:`)
 			p.addSourceMapping(loc.Loc{Start: eqStart + 1})
 			p.print(`"` + encodeDoubleQuote(a.Val) + `"`)
-			endLoc = eqStart + 1 + len(a.Val) + 2
```
Comment (natemoo-re) [inline internal/printer/print-to-tsx.go:378]: Turns out these would mess up the `endLoc` because they could be out of order

File: internal/printer/print-to-tsx.go [hunk 2]
```diff
@@ -436,6 +432,9 @@ declare const Astro: Readonly<import('astro').AstroGlobal<%s>>`, props.Ident)
 				p.addSourceMapping(loc.Loc{Start: endLoc})
 				endLoc++
 				break
+			} else if unicode.IsSpace(rune(c)) {
+				hasLeadingSpace = true
+				endLoc++
```
Comment (natemoo-re) [inline internal/printer/print-to-tsx.go:437]: If we find a space before the `>`, we flag it

File: internal/printer/print-to-tsx.go [hunk 3]
```diff
@@ -444,13 +443,16 @@ declare const Astro: Readonly<import('astro').AstroGlobal<%s>>`, props.Ident)
 		endLoc++
 	}
 
+	if hasLeadingSpace {
+		p.addSourceMapping(loc.Loc{Start: endLoc - 1})
+		p.print(" ")
+	}
```
Comment (natemoo-re) [inline internal/printer/print-to-tsx.go:449]: And if we have the flag, we print an extra `" "` character

**Review by Princesseuh — APPROVED** [review]
Logic seems fine to me, but I have one question, what happens if there's multiple spaces?

```ts
<Button      >
```

Will they all get mapped to the first space that was created, since only one space is created?

**Comment by natemoo-re** [comment]
Great question @Princesseuh! I just pushed a change to make the mapping a bit more clear for that case—that one space technically gets mapped back to the whole block of spaces in the source file. I think TypeScript should handle this just fine, but we can adjust if that's not the case.
