### PR TITLE
fix(#221): fix tokenization of `/` inside expression attributes

### LINKED ISSUE #221: 🐛 BUG: Can't perform maths using variables inside the JSX {} operator
### What version of `@astrojs/compiler` are you using?

0.5.7

### What package manager are you using?

yarn

### What operating system are you using?

Ubuntu

### Describe the Bug

I am facing the following error when trying to set `(height * 100) / width` as the value of any attribute.

image

And this error when used inside an element,

image

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hua66y?file=src%2Fpages%2Findex.astro

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Closes #221
- Fixes tokenization of expression attributes when `/` is used (now breaks on closing `}`, if it exists)

## Testing

Tests added

## Docs

Bug fix only

### CODE REVIEW

File: internal/token.go [hunk 1]
```diff
@@ -1236,7 +1236,13 @@ func (z *Tokenizer) readTagAttrExpression() {
 				if next == '/' {
 					panic("Block comments (//) are not allowed inside of expressions")
 				}
-				z.readCommentOrRegExp()
+				// Also stop when we hit a '}' character (end of attribute expression)
+				z.readCommentOrRegExp([]byte{'}'})
```
Comment (natemoo-re) [inline internal/token.go:1240]: Previously, we were only doing `z.readCommentOrRegExp()` which didn't know what to do with a single `/` character (it assumed it was part of a RegExp literal.

Now `readCommentOrRegExp` accepts additional characters that can be considered a boundary, like `}`.

File: internal/token.go [hunk 2]
```diff
@@ -1236,7 +1236,13 @@ func (z *Tokenizer) readTagAttrExpression() {
...
+				// If we exit on a '}', ignore the final character here
+				lastChar := z.buf[z.data.End-1 : z.data.End][0]
+				if lastChar == '}' {
+					z.data.End--
+				}
```
Comment (natemoo-re) [inline internal/token.go:1245]: This checks if the final character was `}`, in which case we need to do `z.data.End--` to back up and re-process the character in this loop.

**Review by jonathantneal — APPROVED** [review]
Solid. Appreciate the comment above the check logic, too.
