### PR TITLE
Fix content treated as string after JSX comment inside expression

### LINKED ISSUE #609: Error when comment is in JS expression
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm 

### What operating system are you using?

Mac

### Describe the Bug

When adding a comment to a mapped JS expression, the compiler errors:

```astro
{fontCSSURLs.map((fontCSSURL) => (
  <Fragment>
    <!-- See https://csswizardry.com/2020/05/the-fastest-google-fonts/#google-fonts-async-snippet -->
    <link rel="stylesheet" href={fontCSSURL} media="print" onload="this.media='all'" />
    <noscript>
      <link rel="stylesheet" href={fontCSSURL} />
    </noscript>
  </Fragment>
))}
```
^ this errors (fontCSSURLs is a list of string)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-k999x5?file=src/pages/index.astro&view=editor

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by MoustaphaDev**
## Changes

Partial fix for #609

Fix the issues where HTML and JSX comments lead to subsequent content being incorrectly treated as plain text when they have parent expressions.

#897 will fix the final issue mentioned in #609 which is kind of unrelated to JSX comments being used, but expressions in general

## Testing

Added printer test for each case mentioned in the issue

## Docs

N/A bug fix

### CODE REVIEW

File: internal/printer/printer_test.go [hunk 1]
```diff
@@ -2804,7 +2856,7 @@ const items = ["Dog", "Cat", "Platipus"];
...
+				code: `${($$render` + BACKTICK + `${$$renderComponent($$result,'Fragment',Fragment,{},{"default": () => $$render` + BACKTICK + `${$$renderComponent($$result,'Fragment',Fragment,{},{"default": () => $$render` + BACKTICK + `${$$unescapeHTML(` + BACKTICK + `<${Node.tag} ${stringifyAttributes(Node.attributes)}>` + BACKTICK + `)}` + BACKTICK + `,})}${Node.children.map((child) => ($$render` + BACKTICK + `${$$renderComponent($$result,'Astro.self',Astro.self,{"node":(child)})}` + BACKTICK + `))}${$$renderComponent($$result,'Fragment',Fragment,{},{"default": () => $$render` + BACKTICK + `${$$unescapeHTML(` + BACKTICK + `</${Node.tag}>` + BACKTICK + `)}` + BACKTICK + `,})}` + BACKTICK + `,})}` + BACKTICK + `)}`,
```
Comment (MoustaphaDev) [inline internal/printer/printer_test.go:2859]: The backtick wasn't placed in the right spot, [see this](https://live-astro-compiler.vercel.app/?editor-state=WzMxLDEzOSw4LDAsMjI4LDEwNiw5NSwxMDEsMiwzLDEwOSwxNDMsMjA1LDEwNiwxOTUsNDgsMTYsMTMyLDk1LDY5LDEzNiwyOCwxMDgsOCwyMDYsMjIxLDIxNiwxMzQsMTYsOCwyMCw3NCw0MSw5LDE2NSwyMTUsMTA4LDE3MywxODEsMzUsMjA4LDE0MywxNDUsMjE0LDE0OCw4NiwyMzIsMjIxLDQzLDIxOSw4NCwyMzcsMzMsMTgzLDIyMSwxNTcsMTExLDcwLDE2MywxOTIsMTIzLDQzLDE0NCwyMTUsNjAsMjAsMjA1LDIxNywxOTMsMTY4LDIwOSw4MCwxNTEsMzksMjMwLDE0NSwyMzQsNTksMTA1LDIxMywxMzQsOTEsMTc5LDExLDQ3LDksMTczLDgsMTk4LDIwMCwxMTgsMTkzLDE0NywxNDcsMTAyLDE0OCwxOTUsMjE1LDE0NSwyMTAsMjQ0LDQ5LDE5LDI1MCw5OCwyMTMsMzMsMjM5LDEwMSwyMzYsMTEwLDE0NSwyOSwxODYsMjA1LDIxNSwyMjMsMTY1LDE4LDE0LDc3LDE2NSw5Nyw0MiwxMzgsMTE3LDQzLDg5LDIxOSwxNzcsMTYyLDU3LDE2Niw0NCw5MSwxMjEsODQsMyw1MSwxMzcsMTA4LDE5NSw0Miw0NiwyMDYsMTc4LDE0MCwxNDMsMTg3LDI4LDI1NCwxNDksMjE3LDMwLDEwNSwxNCwxODUsMTI2LDI1LDI0OSwxNTgsMTI3LDkwLDM5LDIyMiwyOSw3NiwxOSwxMCw5NCwxNSwxNjAsNjAsMjM4LDE4NSwyMjIsMTkwLDc0LDE0LDE0MCwzMSwxNzIsMjExLDksMTU1LDE5MiwxMjEsMTI0LDE4MSw5NCwxNDYsMTgwLDEzNCwyMTUsMjI4LDIzMCwxOTYsMTAxLDIyNCwyMDEsMTYsNTgsMywyMzQsMjM3LDI0MiwxNTYsMTI0LDksMzEsMTY0LDY2LDMsMTIyLDczLDU3LDEyOSwxOSwyMSw0NCwyMTMsMjExLDIyMSwzNiwyNCwxNDgsMjUyLDcwLDExMywyNTQsMzUsMjEwLDYxLDM5LDE1NywxNzIsMTU4LDE2MCwxNjcsOTIsMzcsMTEsMjMsMjQ0LDE3OSwxNjIsMTA3LDExMSw4MywyMDksMTcxLDE3OCwxOTEsNjgsMjUyLDEsMTEzLDIyMCwxMDIsMjcsMTUzLDEsMCwwXQ%3D%3D) for a visualisation, the parenthesis wasn't closed.
This PR fixes unintentionally this too!

File: .changeset/lazy-beers-develop.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@astrojs/compiler': patch
+---
+
+Fix issue where HTML and JSX comments lead to subsequent content being incorrectly treated as plain text when they have parent expressions.
```
Comment (sarah11918) [inline .changeset/lazy-beers-develop.md:5]:
```suggestion
Fixes an issue where HTML and JSX comments lead to subsequent content being incorrectly treated as plain text when they have parent expressions.
```

**Review by sarah11918 — COMMENTED** [review]
Just updating the changeset to match the verb tense we're standardizing on! 🙌

File: internal/helpers/js_comment_utils.go [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+)
+
+// RemoveComments removes both block and inline comments from a string
+func RemoveComments(input string) (string, error) {
+	var (
+		sb        = strings.Builder{}
+		inComment = false
+	)
+	for cur := 0; cur < len(input); cur++ {
+		peekIs := func(assert byte) bool { return cur+1 < len(input) && input[cur+1] == assert }
```
Comment (matthewp) [inline internal/helpers/js_comment_utils.go:15]: can you move this function to above the loop? This also means needing to move the `cur := 0` above as well. I don't know how the Go compiler works but naively it might be creating a new closure for each iteration of the loop which is quite expensive when looping over a string. Lifting it up should help if that's the case.

File: internal/printer/print-to-js.go [hunk 4]
```diff
@@ -87,13 +88,18 @@ func printToJs(p *printer, n *Node, cssLen int, opts transform.TransformOptions)
...
 
 // Returns true if the expression only contains a comment block (e.g. {/* a comment */})
-func expressionOnlyHasCommentBlock(n *Node) bool {
-	clean, _ := removeComments(n.FirstChild.Data)
-	return n.FirstChild.NextSibling == nil &&
+func expressionOnlyHasComment(n *Node) bool {
+	if n.FirstChild == nil {
+		return false
+	}
+	clean, _ := helpers.RemoveComments(n.FirstChild.Data)
```
Comment (matthewp) [inline internal/printer/print-to-js.go:95]: RemoveComments can return an error. Shouldn't we be handling it?

File: internal/printer/printer_test.go [hunk 5]
```diff
@@ -811,6 +811,20 @@ const groups = [[0, 1, 2], [3, 4, 5]];
 				code: "${$$maybeRenderHead($$result)}<body><!-- \\`npm install astro\\` --></body>",
 			},
 		},
+		{
+			name:   "HTML comment in component inside expression I",
+			source: "{(() => <Component><!--Hi--></Component>)}",
+			want: want{
+				code: "${(() => $$render`${$$renderComponent($$result,'Component',Component,{},{})}`)}",
```
[the remark this answers is not in the document]
Comment (MoustaphaDev) [reply internal/printer/printer_test.go:818]: Oh that's true, I'll fix that

File: internal/helpers/js_comment_utils.go (hunk 3 above)
Comment (MoustaphaDev) [reply internal/helpers/js_comment_utils.go:15]: Yeah I'll move it out of the function entirely, it's only used three times in the functions, won't hurt passing the arguments manually three times 😄

File: internal/printer/print-to-js.go (hunk 4 above)
Comment (MoustaphaDev) [reply internal/printer/print-to-js.go:95]: Wasn't handled before, but yes we probably should

File: internal/printer/printer_test.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (MoustaphaDev) [reply internal/printer/printer_test.go:818]: Actually, it looks like comments should not be slotted, I found a [test case](https://github.com/withastro/compiler/blob/0bfdc2d0763bd79ccc44bd722bb19b8daec9b668/internal/printer/printer_test.go#L961) for that. Here's [another test](https://github.com/withastro/compiler/blob/0bfdc2d0763bd79ccc44bd722bb19b8daec9b668/internal/printer/printer_test.go#L809) showing comments being preserved outside component slots

File: internal/printer/print-to-js.go (hunk 4 above)
Comment (MoustaphaDev) [reply internal/printer/print-to-js.go:95]: Looking at it again now, I think it's safe to ignore comments. We already handle unterminated js and html comments in the tokenizer.
https://github.com/withastro/compiler/blob/a8a845f84b08dd4a4e50f5dd433f0350155c7937/internal/token.go#L1030-L1039
https://github.com/withastro/compiler/blob/a8a845f84b08dd4a4e50f5dd433f0350155c7937/internal/token.go#L907-L916

I'll refactor the RemoveComments function to only return strings.

**Comment by MoustaphaDev** [comment]
!preview err-jsx-comments-in-expr

File: internal/printer/printer_test.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (natemoo-re) [reply internal/printer/printer_test.go:818]: Ah you're totally correct, it would be strange to pass these comments into framework components. I didn't think about this being _inside_ of the `<Component>` node.

**Review by natemoo-re — APPROVED** [review]
Looks great, thanks for the PR!
