### PR TITLE
fix(tokenizer): handle unterminated quoted attributes gracefully

### LINKED ISSUE #904: 🐛 BUG: Unbalanced quotes in HTML attributes crashes compiler when parsing AST
### What version of `@astrojs/compiler` are you using?

^2.2.2

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### Describe the Bug

The following code: `<main id="gotcha />` crashes the compiler due to the missing end quote.

For more details, see the following issue: https://github.com/withastro/language-tools/issues/623

### Link to Minimal Reproducible Example

See description

### PR DESCRIPTION
**Pull request by MoustaphaDev**
## Changes

- Fix #904
- Complement to #636.

Fix an issue where unterminated quoted attributes caused the compiler to crash

## Testing

Added a TSX output test to make sure the compiler doesn't crash

## Docs
N/A bug fix

### CODE REVIEW

**Comment by Princesseuh** [comment]
The crash only happened in the AST printing. Could a test be added for that too?

**Comment by MoustaphaDev** [comment]
Sure, I'll add that

File: internal/printer/printer_test.go [hunk 1]
```diff
@@ -3277,6 +3277,16 @@ const c = '\''
 			source: `<html><body><h1>Hello world!</h1><style></style></body></html>`,
 			want:   []ASTNode{{Type: "element", Name: "html", Children: []ASTNode{{Type: "element", Name: "body", Children: []ASTNode{{Type: "element", Name: "h1", Children: []ASTNode{{Type: "text", Value: "Hello world!"}}}, {Type: "element", Name: "style"}}}}}},
 		},
+		{
+			name:   "element with unterminated double quote attribute",
+			source: `<main id="gotcha />`,
+			want:   []ASTNode{{Type: "element", Name: "main", Attributes: []ASTNode{{Type: "attribute", Kind: "quoted", Name: "id", Value: "", Raw: "\"g"}}}},
```
Comment (MoustaphaDev) [inline internal/printer/printer_test.go:3283]: I wonder if the `"g` in the `Raw` property is expected, I don't have context on why it would behave like this and don't want to assume that it's a bug

Comment (Princesseuh) [reply internal/printer/printer_test.go:3283]: Heh, I'd say that it's kinda partially expected, you can't have a valid raw value without the ending quote

Comment (MoustaphaDev) [reply internal/printer/printer_test.go:3283]: Yeah makes sense, I'll probably use a heuristic like stopping at the first non-alphabetic character. Waiting to get roasted 🫣

File: internal/printer/print-to-json.go [hunk 2]
```diff
@@ -230,7 +230,7 @@ func renderNode(p *printer, parent *ASTNode, n *Node, opts t.ParseOptions) {
 				}
 				position := attrPositionAt(p, &attr, opts)
 				raw := ""
-				if attr.Type == QuotedAttribute {
+				if attr.Type == QuotedAttribute || attr.Type == TemplateLiteralAttribute {
```
Comment (MoustaphaDev) [inline internal/printer/print-to-json.go:233]: Updated this to also include *some* of the raw unterminated template literal attribute value

File: internal/token.go [hunk 3]
```diff
@@ -1463,7 +1485,17 @@ func (z *Tokenizer) readTagAttrVal() {
 			c := z.readByte()
 			if z.err != nil {
 				if z.err == io.EOF {
-					z.pendingAttr[1].End = z.pendingAttr[1].Start
+					for i := z.pendingAttr[1].Start; i < z.raw.End; i++ {
+						c := z.buf[i]
+						if unicode.IsSpace(rune(c)) || c == '/' || c == '>' {
```
Comment (natemoo-re) [inline internal/token.go:1490]:
```suggestion
					// rescan, closing any potentially unterminated attribute values
					for i := z.pendingAttr[1].Start; i < z.raw.End; i++ {
						c := z.buf[i]
						if unicode.IsSpace(rune(c)) || c == '/' || c == '>' {
```

**Review by natemoo-re — APPROVED** [review]
This is great!

**Comment by MoustaphaDev** [comment]
I'm out of my desk right now, I'll fix the failing tests (probably impacted by the recent merged PRs)

**Comment by MoustaphaDev** [comment]
I suspect this tests failure to be caused by my PR in https://github.com/withastro/compiler/pull/930, I'll investigate further

**Comment by MoustaphaDev** [comment]
Tests should pass after merging https://github.com/withastro/compiler/pull/932
