### PR TITLE
fix(#225): Do not treat `noscript` as raw

### LINKED ISSUE #225: 🐛 BUG: Components inside <noscript> are not parsed through the compiler
### What version of `astro` are you using?

0.21.13

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Any components in a `<noscript>` tag only pass in the source code. It does not get parsed through the compiler.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8nksfd?file=src/pages/index.astro

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Closes #225
- Removes `noscript` from the list of tags to tokenize as raw text

## Testing

Tests added in tokenizer and printer

## Docs

Bug fix only

### CODE REVIEW

File: internal/token_test.go [hunk 1]
```diff
@@ -44,6 +44,11 @@ func TestBasic(t *testing.T) {
 			`<pkg.Item>`,
 			[]TokenType{StartTagToken},
 		},
+		{
+			"noscript component",
+			`<noscript><Component /></noscript>`,
+			[]TokenType{StartTagToken, SelfClosingTagToken, EndTagToken},
```
Comment (natemoo-re) [inline internal/token_test.go:50]: Previously all contents inside of `noscript` were tokenized as `TextToken` instead of being tokenized as regular content.

File: internal/token.go [hunk 2]
```diff
@@ -957,7 +957,7 @@ func (z *Tokenizer) readStartTag() TokenType {
 	case 'i':
 		raw = z.startTagIn("iframe")
 	case 'n':
-		raw = z.startTagIn("noembed", "noframes", "noscript")
+		raw = z.startTagIn("noembed", "noframes")
```
Comment (natemoo-re) [inline internal/token.go:960]: Removing `noscript` from this `raw` logic fixes that!

**Review by jonathantneal — APPROVED** [review]
This makes sense. Server parsing versus client parsing. 👍
