### PR TITLE
fix(#223): Do not prefix values inside of declarations

### LINKED ISSUE #223: 🐛 BUG: grid-template-* with [line-name] adds extra astro class
### What version of `astro` are you using?

^0.21.10

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When adding `grid-template-columns` in a style tag with line-names, like this:

`grid-template-columns: [content-start] 1fr [content-end];`

an extra .astro class is entered into the style value, generating this:

`grid-template-columns: .astro-4D2SJCT3[content-start] 1fr [content-end]`

which is invalid CSS.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rfg3sg?file=src/components/Tour.astro

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Fixes #223
- Improves our scoping algorithm to not touch values inside of declaration rules (like `grid-template-column`.

## Testing

Test added

## Docs

Bug fix only

### CODE REVIEW

File: internal/transform/scope-css.go [hunk 1]
```diff
@@ -35,6 +35,7 @@ outer:
 
 		isKeyframes := false    // if we’re inside @keyframes, there’s nothing to scope
 		keyframeCurlyCount := 0 // keep track of open "{"s inside @keyframes
+		declaration := ""
```
Comment (natemoo-re) [inline internal/transform/scope-css.go:38]: This tracks any `css.DeclarationGramar` nodes that we enter.

File: internal/transform/scope-css.go [hunk 2]
```diff
@@ -69,6 +70,7 @@ outer:
 					}
 				case css.DeclarationGrammar:
 					out += string(data) + ":"
+					declaration = string(data)
```
Comment (natemoo-re) [inline internal/transform/scope-css.go:73]: Set the `declaration` flag. Just used as a boolean flag.

File: internal/transform/scope-css.go [hunk 3]
```diff
@@ -122,8 +124,9 @@ outer:
 						isBracket = true
 						isElement = false
 						isPseudoState = false
-						// if there is no selector before an attribute selector, then assume "*"
-						if n == 0 {
+
+						// if there is no selector before an attribute selector and we're not in a delcaration, assume "*"
+						if n == 0 && declaration == "" {
```
Comment (natemoo-re) [inline internal/transform/scope-css.go:129]: Previously, this logic was designed to handle attribute selectors `[data-click]` but it _also_ unintentionally caught cases like:
```
grid-template-columns: [content-start] 1fr [content-end];
```

This fixes that by checking if we've already encountered a declaration.

**Review by jonathantneal — APPROVED** [review]
I’m so glad the fix for this is logical (with the "i am within a declaration value, do not touch" flag)
