### PR TITLE
Replace internal logs with properly handled warnings

### LINKED ISSUE #647: 🐛 BUG: Unclosed style tag crash the compiler
### What version of `@astrojs/compiler` are you using?

0.29.17

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### Describe the Bug

When encountering an unclosed style tag, the compiler crashes with the following stacktrace:

image

This is easy to reproduce in the TSX output in the editor, as writing `<style>` will instantly crash the extension. This is not specific to the TSX output though, as an error also shows up in Astro when doing that:
image

### Link to Minimal Reproducible Example

File with just `<style>` will do it

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Closes #647
- Replaces `fmt.Printf` statements in the tokenizer with proper warnings for unexpected characters. 
- Gracefully handles EOF now

## Testing

Test added

## Docs

Bug fix only

### CODE REVIEW

**Review by Princesseuh — APPROVED** [review]

File: packages/compiler/test/bad-styles/unclosed-style.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+import { parse } from '@astrojs/compiler';
+
+test('can compile unfinished style', async () => {
+  let error = 0;
+  try {
+    await parse(`<style>`);
+  } catch (e) {
+    error = 1;
+  }
+  assert.equal(error, 0, 'Expected to compile with unfinished style.');
```
Comment (jasikpark) [inline packages/compiler/test/bad-styles/unclosed-style.ts:12]: wouldn't it make sense to also assert on the output if this is expected to not error?
